
import { Course } from './types';

export const COURSE_TABS = [
  'Python',
  'Excel',
  'Web Development',
  'JavaScript',
  'Data Science',
  'AWS Certification',
  'Drawing',
];

export const COURSES: { [key: string]: Course[] } = {
  'Python': [
    {
      id: 1,
      title: 'The Complete Python Bootcamp From Zero to Hero in Python',
      instructor: 'Jose Portilla',
      image: 'https://picsum.photos/seed/python1/300/170',
      rating: 4.6,
      reviews: 463771,
      price: '$14.99',
      originalPrice: '$84.99',
      bestseller: true,
      tag: 'Python',
    },
    {
      id: 2,
      title: 'Automate the Boring Stuff with Python Programming',
      instructor: 'Al Sweigart',
      image: 'https://picsum.photos/seed/python2/300/170',
      rating: 4.7,
      reviews: 111535,
      price: '$14.99',
      originalPrice: '$84.99',
      bestseller: true,
      tag: 'Python',
    },
    {
      id: 3,
      title: '100 Days of Code: The Complete Python Pro Bootcamp for 2024',
      instructor: 'Dr. Angela Yu',
      image: 'https://picsum.photos/seed/python3/300/170',
      rating: 4.7,
      reviews: 284534,
      price: '$14.99',
      originalPrice: '$84.99',
      bestseller: true,
      tag: 'Python',
    },
     {
      id: 4,
      title: 'Python for Data Science and Machine Learning Bootcamp',
      instructor: 'Jose Portilla',
      image: 'https://picsum.photos/seed/python4/300/170',
      rating: 4.6,
      reviews: 139414,
      price: '$14.99',
      originalPrice: '$84.99',
      tag: 'Python',
    },
    {
      id: 5,
      title: 'The Python Mega Course: Build 10 Real World Applications',
      instructor: 'Ardit Sulce',
      image: 'https://picsum.photos/seed/python5/300/170',
      rating: 4.6,
      reviews: 80112,
      price: '$14.99',
      originalPrice: '$84.99',
      tag: 'Python',
    },
  ],
  'Excel': [
    {
      id: 11,
      title: 'Microsoft Excel - Excel from Beginner to Advanced',
      instructor: 'Kyle Pew, Office Newb',
      image: 'https://picsum.photos/seed/excel1/300/170',
      rating: 4.7,
      reviews: 387492,
      price: '$14.99',
      originalPrice: '$84.99',
      bestseller: true,
      tag: 'Excel',
    },
    {
      id: 12,
      title: 'Microsoft Excel - Data Analysis with Excel Pivot Tables',
      instructor: 'Maven Analytics',
      image: 'https://picsum.photos/seed/excel2/300/170',
      rating: 4.6,
      reviews: 98453,
      price: '$12.99',
      originalPrice: '$79.99',
      bestseller: true,
      tag: 'Excel',
    },
    {
      id: 15,
      title: 'Microsoft Excel - Data Visualization, Charts & Graphs',
      instructor: 'Maven Analytics',
      image: 'https://picsum.photos/seed/excel3/300/170',
      rating: 4.6,
      reviews: 54321,
      price: '$12.99',
      originalPrice: '$79.99',
      tag: 'Excel',
    },
  ],
  'Web Development': [
    {
      id: 6,
      title: 'The Complete 2024 Web Development Bootcamp',
      instructor: 'Dr. Angela Yu',
      image: 'https://picsum.photos/seed/webdev1/300/170',
      rating: 4.7,
      reviews: 350123,
      price: '$19.99',
      originalPrice: '$99.99',
      bestseller: true,
      tag: 'Web Dev',
    },
    {
      id: 7,
      title: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
      instructor: 'Maximilian Schwarzmüller',
      image: 'https://picsum.photos/seed/webdev2/300/170',
      rating: 4.6,
      reviews: 180432,
      price: '$19.99',
      originalPrice: '$99.99',
      bestseller: true,
      tag: 'React',
    },
    {
      id: 10,
      title: 'Angular - The Complete Guide (2024 Edition)',
      instructor: 'Maximilian Schwarzmüller',
      image: 'https://picsum.photos/seed/angular1/300/170',
      rating: 4.6,
      reviews: 198754,
      price: '$14.99',
      originalPrice: '$84.99',
      bestseller: true,
      tag: 'Angular',
    },
  ],
  'JavaScript': [
     {
      id: 8,
      title: 'The Complete JavaScript Course 2024: From Zero to Expert!',
      instructor: 'Jonas Schmedtmann',
      image: 'https://picsum.photos/seed/js1/300/170',
      rating: 4.7,
      reviews: 191345,
      price: '$14.99',
      originalPrice: '$84.99',
      bestseller: true,
      tag: 'JavaScript',
    },
  ],
  'Data Science': [
    {
      id: 9,
      title: 'The Data Science Course 2024: Complete Data Science Bootcamp',
      instructor: '365 Careers',
      image: 'https://picsum.photos/seed/dscience1/300/170',
      rating: 4.6,
      reviews: 139123,
      price: '$16.99',
      originalPrice: '$89.99',
      bestseller: true,
      tag: 'Data Science',
    },
     {
      id: 4,
      title: 'Python for Data Science and Machine Learning Bootcamp',
      instructor: 'Jose Portilla',
      image: 'https://picsum.photos/seed/python4/300/170',
      rating: 4.6,
      reviews: 139414,
      price: '$14.99',
      originalPrice: '$84.99',
      tag: 'Python',
    },
  ],
  'AWS Certification': [
    {
      id: 13,
      title: '[NEW] Ultimate AWS Certified Solutions Architect Associate',
      instructor: 'Stephane Maarek',
      image: 'https://picsum.photos/seed/aws1/300/170',
      rating: 4.7,
      reviews: 215321,
      price: '$14.99',
      originalPrice: '$84.99',
      bestseller: true,
      tag: 'AWS',
    },
  ],
  'Drawing': [
     {
      id: 14,
      title: 'The Ultimate Drawing Course - Beginner to Advanced',
      instructor: 'Jaysen Arts, Quinton Batchelor',
      image: 'https://picsum.photos/seed/drawing1/300/170',
      rating: 4.6,
      reviews: 102934,
      price: '$14.99',
      originalPrice: '$84.99',
      bestseller: true,
      tag: 'Drawing',
    },
  ]
};

export const STUDENTS_VIEWING_COURSES: Course[] = [
  {
    id: 9,
    title: 'The Data Science Course 2024: Complete Data Science Bootcamp',
    instructor: '365 Careers',
    image: 'https://picsum.photos/seed/dscience1/300/170',
    rating: 4.6,
    reviews: 139123,
    price: '$16.99',
    originalPrice: '$89.99',
    bestseller: true,
    tag: 'Data Science',
  },
  {
    id: 10,
    title: 'Angular - The Complete Guide (2024 Edition)',
    instructor: 'Maximilian Schwarzmüller',
    image: 'https://picsum.photos/seed/angular1/300/170',
    rating: 4.6,
    reviews: 198754,
    price: '$14.99',
    originalPrice: '$84.99',
    bestseller: true,
    tag: 'Angular',
  },
  {
    id: 1,
    title: 'The Complete Python Bootcamp From Zero to Hero in Python',
    instructor: 'Jose Portilla',
    image: 'https://picsum.photos/seed/python1/300/170',
    rating: 4.6,
    reviews: 463771,
    price: '$14.99',
    originalPrice: '$84.99',
    bestseller: true,
    tag: 'Python',
  },
  {
    id: 6,
    title: 'The Complete 2024 Web Development Bootcamp',
    instructor: 'Dr. Angela Yu',
    image: 'https://picsum.photos/seed/webdev1/300/170',
    rating: 4.7,
    reviews: 350123,
    price: '$19.99',
    originalPrice: '$99.99',
    bestseller: true,
    tag: 'Web Dev',
  },
  {
    id: 8,
    title: 'The Complete JavaScript Course 2024: From Zero to Expert!',
    instructor: 'Jonas Schmedtmann',
    image: 'https://picsum.photos/seed/js1/300/170',
    rating: 4.7,
    reviews: 191345,
    price: '$14.99',
    originalPrice: '$84.99',
    bestseller: true,
    tag: 'JavaScript',
  },
  {
      id: 11,
      title: 'Microsoft Excel - Excel from Beginner to Advanced',
      instructor: 'Kyle Pew, Office Newb',
      image: 'https://picsum.photos/seed/excel1/300/170',
      rating: 4.7,
      reviews: 387492,
      price: '$14.99',
      originalPrice: '$84.99',
      bestseller: true,
      tag: 'Excel',
  },
];


export const CATEGORIES = [
  'Development',
  'Business',
  'Finance & Accounting',
  'IT & Software',
  'Office Productivity',
  'Personal Development',
  'Design',
  'Marketing',
  'Lifestyle',
  'Photography & Video',
  'Health & Fitness',
  'Music',
  'Teaching & Academics',
];

export const FOOTER_LINKS = {
    "Udemy Business": ["Teach on Udemy", "Get the app", "About us", "Contact us"],
    "Careers": ["Blog", "Help and Support", "Affiliate", "Investors"],
    "Terms": ["Privacy policy", "Cookie settings", "Sitemap", "Accessibility statement"],
};