import { Course } from '../types';

export const ALL_COURSES: Course[] = [
    {
      id: 1,
      title: 'The Complete Python Bootcamp From Zero to Hero in Python',
      instructor: 'Jose Portilla',
      image: 'https://picsum.photos/seed/python1/480/270',
      rating: 4.6,
      reviews: 463771,
      price: 14.99,
      originalPrice: 84.99,
      bestseller: true,
      category: 'Python',
      subtitle: 'Learn Python like a Professional Start from the basics and go all the way to creating your own applications and games.',
      students: 1675333,
      lastUpdated: '9/2023',
      language: 'English',
      whatYoullLearn: [
        'Learn to use Python professionally, learning both Python 2 and Python 3!',
        'Create games with Python, like Tic Tac Toe and Blackjack!',
        'Learn advanced Python features, like the collections module and how to work with timestamps!',
        'Learn to use Object Oriented Programming with classes!',
        'Understand complex topics, like decorators.',
        'Understand how to use both the Jupyter Notebook and create .py files.',
        'Get an understanding of how to create GUIs in the Jupyter Notebook system!',
        'Build a complete understanding of Python from the ground up!'
      ],
      requirements: [
        'Access to a computer with an internet connection.'
      ],
      longDescription: 'Become a Python Programmer and learn one of employer\'s most requested skills of 2024! This is the most comprehensive, yet straight-forward, course for the Python programming language on Udemy! Whether you have never programmed before, already know basic syntax, or want to learn about the advanced features of Python, this course is for you! In this course we will teach you both Python 2 and Python 3. With over 100 lectures and more than 21 hours of video this comprehensive course leaves no stone unturned! This course includes quizzes, tests, coding exercises and homework assignments as well as 3 major projects to create a Python project portfolio!.',
      instructorBio: 'Jose Portilla has a BS and MS in Mechanical Engineering from Santa Clara University and years of experience as a professional instructor and trainer for Data Science and programming. He has publications and patents in various fields such as microfluidics, materials science, and data science technologies. Over the course of his career he has developed a skill set in analyzing data and he hopes to use his experience in teaching and data science to help other people learn the power of programming, the ability to analyze data, and present the data in clear and beautiful visualizations. ',
      courseContent: [
        { 
          sectionTitle: 'Course Introduction',
          lectures: [
            { title: 'Course Introduction', duration: '08:22' },
            { title: 'Course Curriculum Overview', duration: '04:55' }
          ]
        },
        { 
          sectionTitle: 'Python Setup',
          lectures: [
            { title: 'Command Line Basics', duration: '11:21' },
            { title: 'Installing Python (Step by Step)', duration: '12:44' },
            { title: 'Running Python Code', duration: '07:32' }
          ]
        },
        { 
          sectionTitle: 'Python Object and Data Structure Basics',
          lectures: [
            { title: 'Introduction to Python Data Types', duration: '03:12' },
            { title: 'Numbers', duration: '08:55' },
            { title: 'Strings', duration: '19:01' },
            { title: 'Lists', duration: '15:32' }
          ]
        }
      ]
    },
    {
      id: 2,
      title: 'Automate the Boring Stuff with Python Programming',
      instructor: 'Al Sweigart',
      image: 'https://picsum.photos/seed/python2/480/270',
      rating: 4.7,
      reviews: 111535,
      price: 14.99,
      originalPrice: 84.99,
      bestseller: true,
      category: 'Python',
    },
    {
      id: 3,
      title: '100 Days of Code: The Complete Python Pro Bootcamp for 2024',
      instructor: 'Dr. Angela Yu',
      image: 'https://picsum.photos/seed/python3/480/270',
      rating: 4.7,
      reviews: 284534,
      price: 14.99,
      originalPrice: 84.99,
      bestseller: true,
      category: 'Python',
    },
     {
      id: 4,
      title: 'Python for Data Science and Machine Learning Bootcamp',
      instructor: 'Jose Portilla',
      image: 'https://picsum.photos/seed/python4/480/270',
      rating: 4.6,
      reviews: 139414,
      price: 14.99,
      originalPrice: 84.99,
      category: 'Python',
    },
    {
      id: 5,
      title: 'The Python Mega Course: Build 10 Real World Applications',
      instructor: 'Ardit Sulce',
      image: 'https://picsum.photos/seed/python5/480/270',
      rating: 4.6,
      reviews: 80112,
      price: 14.99,
      originalPrice: 84.99,
      category: 'Python',
    },
    {
      id: 11,
      title: 'Microsoft Excel - Excel from Beginner to Advanced',
      instructor: 'Kyle Pew, Office Newb',
      image: 'https://picsum.photos/seed/excel1/480/270',
      rating: 4.7,
      reviews: 387492,
      price: 14.99,
      originalPrice: 84.99,
      bestseller: true,
      category: 'Excel',
    },
    {
      id: 12,
      title: 'Microsoft Excel - Data Analysis with Excel Pivot Tables',
      instructor: 'Maven Analytics',
      image: 'https://picsum.photos/seed/excel2/480/270',
      rating: 4.6,
      reviews: 98453,
      price: 12.99,
      originalPrice: 79.99,
      bestseller: true,
      category: 'Excel',
    },
    {
      id: 15,
      title: 'Microsoft Excel - Data Visualization, Charts & Graphs',
      instructor: 'Maven Analytics',
      image: 'https://picsum.photos/seed/excel3/480/270',
      rating: 4.6,
      reviews: 54321,
      price: 12.99,
      originalPrice: 79.99,
      category: 'Excel',
    },
    {
      id: 6,
      title: 'The Complete 2024 Web Development Bootcamp',
      instructor: 'Dr. Angela Yu',
      image: 'https://picsum.photos/seed/webdev1/480/270',
      rating: 4.7,
      reviews: 350123,
      price: 19.99,
      originalPrice: 99.99,
      bestseller: true,
      category: 'Web Development',
    },
    {
      id: 7,
      title: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
      instructor: 'Maximilian Schwarzmüller',
      image: 'https://picsum.photos/seed/webdev2/480/270',
      rating: 4.6,
      reviews: 180432,
      price: 19.99,
      originalPrice: 99.99,
      bestseller: true,
      category: 'Web Development',
    },
    {
      id: 10,
      title: 'Angular - The Complete Guide (2024 Edition)',
      instructor: 'Maximilian Schwarzmüller',
      image: 'https://picsum.photos/seed/angular1/480/270',
      rating: 4.6,
      reviews: 198754,
      price: 14.99,
      originalPrice: 84.99,
      bestseller: true,
      category: 'Web Development',
    },
     {
      id: 8,
      title: 'The Complete JavaScript Course 2024: From Zero to Expert!',
      instructor: 'Jonas Schmedtmann',
      image: 'https://picsum.photos/seed/js1/480/270',
      rating: 4.7,
      reviews: 191345,
      price: 14.99,
      originalPrice: 84.99,
      bestseller: true,
      category: 'JavaScript',
    },
    {
      id: 9,
      title: 'The Data Science Course 2024: Complete Data Science Bootcamp',
      instructor: '365 Careers',
      image: 'https://picsum.photos/seed/dscience1/480/270',
      rating: 4.6,
      reviews: 139123,
      price: 16.99,
      originalPrice: 89.99,
      bestseller: true,
      category: 'Data Science',
    },
    {
      id: 13,
      title: '[NEW] Ultimate AWS Certified Solutions Architect Associate',
      instructor: 'Stephane Maarek',
      image: 'https://picsum.photos/seed/aws1/480/270',
      rating: 4.7,
      reviews: 215321,
      price: 14.99,
      originalPrice: 84.99,
      bestseller: true,
      category: 'AWS Certification',
    },
     {
      id: 14,
      title: 'The Ultimate Drawing Course - Beginner to Advanced',
      instructor: 'Jaysen Arts, Quinton Batchelor',
      image: 'https://picsum.photos/seed/drawing1/480/270',
      rating: 4.6,
      reviews: 102934,
      price: 14.99,
      originalPrice: 84.99,
      bestseller: true,
      category: 'Drawing',
    },
];
